### ISSUE TITLE
Apps consistently fail to launch after a fresh boot. Basic system functionality is affected.

### ISSUE THREAD

**Issue by Photon101** [Vanilla-OS/iso-builder#117]
### Issue Description

The problem is as follows:

After login, flatpak apps and some system apps (such as Files and Console) will refuse to launch after 1 minute has passed, or longer. Sometimes I've noticed the problem occurring at least half an hour into my session. This doesn't happen on every boot, but often enough for it to be a real hassle. This issue can only be resolved temporarily by another reboot.

Once this bug occurs, a list of accompanying problems also show up:
- Some apps like the calculator will launch, but in light mode or at the wrong DPI setting, ignoring the basic system-wide theme configuration.
- You cannot relaunch previously open apps if you close them.
- Logging out of the session doesn't work.
- Gnome Music (if it launches) no longer populates with your music. It says it "cannot connect to Tracker" which it claims isn't running.

This issue is affecting others in the Discord community also. As far as I can tell, the problem only started affecting people after r5, and maybe r6.

### Steps to Reproduce

Install Vanilla OS using the r6 ISO.
Use your PC as normal.
Reboot every once in a while (or often).

### On what version of Vanilla OS this happens?

22.10

**Comment by stpnwf** [comment]
Yes, I've been having this issue as well. I thought at first this was just an X11 thing (bc it had happened every time I used X11), but it also happened under wayland for me. I created [this thread](https://discord.com/channels/1023243680829681704/1070779361399156818) in the Discord server and managed to get some Logs from one of the times it happened:
```
15:37:16 gdm-session-wor: GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
15:37:11 systemd: Failed to start Application launched by gnome-session-binary.
15:37:11 systemd: Failed to start Application launched by gnome-session-binary.
15:37:06 systemd: Failed to start Application launched by gnome-session-binary.
15:37:04 gdm-session-wor: gkr-pam: unable to locate daemon control file
15:37:04 gdm-session-wor: gkr-pam: unable to locate daemon control file
15:36:45 gdm-session-wor: GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
15:36:34 systemd: Failed to start Application launched by gnome-session-binary.
15:36:31 gdm-session-wor: gkr-pam: unable to locate daemon control file
15:36:26 systemd: Failed to start Update the local ESM caches.
15:36:19 kernel: vso-autoupdate.service: Job vso-autoupdate.timer/start deleted to break ordering cycle starting with vso-autoupdate.service/start
15:36:19 kernel: ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_PR_.CPU7 (20220331/dspkginit-438)
```
I had issues even trying to turn off the computer. I couldn't record the screen (video option didn't show up), was only able to capture this:

![Screenshot from 2023-02-02 15-34-21](https://user-images.githubusercontent.com/81482539/216833149-d41e0966-9e29-4a1c-8639-d5b2d30e7b48.png)


I will report here if it happens again

**Comment by ParanoidNemo** [comment]
Same here, I'll drop logs as soon as happens again, last time I've rebooted almost instantly because I need to.

**Comment by mirkobrombin** [comment]
Please read here: https://github.com/Vanilla-OS/os/issues/129#issuecomment-1422756144
Closing, feel free to add more comments if the problem persist.

**Comment by LeatherMolly** [comment]
Hi there,

I am a 3 months fresh vanillaOs user. I came from linuxMint, that I used for more than 10 years. I am mainly used to apt and debian/ ubuntu systems.

I liked Vanilla OS very much in the beginning. But since a while there are a lot of things happening (maybe problems/ maybe bugs/ many freezes...I can't tell).

Right now I want to open "Multiwriter vso-pico", I click it and nothing happens. I click it again, and again and....argh #!#
I don't know how to check why that happens. I am not used to gnome, I get sick using it, because all the needed apps are somewhere hidden, the names of the programs don't show the real names, the Terminal doesn't open in nautilus when I click "open in that folder" and so on and on.

I want to stay with VanillaOs, but it is right now a pain in my A**.

How to adress all this problems to someone who will help, real help with instructions which comands I should type in cli to find out whats the problem?

Thx to every help
Have a good time


...another thing:
why are there two different home folders?
one >/var/home/myusername/
another >/home/myusername/
????
How should I find my data, does that make sense? Which sense?
