### ISSUE TITLE
GNOME Tweaks is missing

### ISSUE THREAD

**Issue by Vittelius** [Vanilla-OS/iso-builder#170]
I can't find GNOME Tweaks. It's not preinstalled (even though the [documentation](https://handbook.vanillaos.org/2022/11/18/first-setup.html#title9) heavily implies it should be) and it doesn't show up in GNOME Software. I haven't tried installing it using apx, because I assume that would install the entire gnome desktop again since in Ubuntu, Tweaks depends on the shell for obvious reasons.

**Comment by GabsEdits** [comment]
> I can't find GNOME Tweaks. It's not preinstalled (even though the [documentation](https://handbook.vanillaos.org/2022/11/18/first-setup.html#title9) heavily implies it should be) and it doesn't show up in GNOME Software. I haven't tried installing it using apx, because I assume that would install the entire gnome desktop again since in Ubuntu, Tweaks depends on the shell for obvious reasons.

Hello @Vittelius , GNOME Tweaks is not preinstalled on Vanilla OS, if you want to install it you **can** install it by using the apx/nix with `apx install -nix gnome.gnome-tweaks` command in your console, or by using ABRoot `sudo abroot exec apt install gnome-tweaks` (it's recommended using apx). It also should not be preinstalled as because Vanilla OS aims to be *"Vanilla"* .

**Comment by Vittelius** [comment]
thanks for the quick reply. marking as closed
