### ISSUE TITLE
Gnome software shows apt source

### ISSUE THREAD

**Issue by secretmango** [Vanilla-OS/iso-builder#183]
### Issue Description

I installed VanillaOS-22.10-all.20230226 in virt-manager

Software doesnt show Flatpak source, which is bad.

But also bad it shows "VanillaOS (apt)" as a source, which makes no sense.

### Steps to Reproduce

- Install it
- Go to software, search for Firefox, check source

### On what version of Vanilla OS this happens?

22.10

**Comment by kbdharun** [comment]
It is expected, to see Vanilla OS curated app stream entries for apx containers. We have our own Gnome software plugin called vanilla meta plugin. It makes sense for applications which recommend installation in a specific distribution like Lutris and when Flatpaks aren't available.

In this case the Firefox app stream entry was a test one to test the plug-in and it wouldn't work because it installs the snap version of it instead of the deb one. There wouldn't be any update for this package in the launchpad as we have migrated our repos to an openSUSE open build system for Orchid (Debian sid migration). Now, we aren't focusing on the app stream entries, but in future you will see a lot of curated ones for installing recommended applications inside a container.

Fun fact: we have another app stream entry for htop other than this, which was also created as a test entry.

Thanks, I will close this issue for now, stay tuned for updates in release notes regarding the app stream entries and meta plugin.
