### ISSUE TITLE
Cannot boot VanillaOS after success installation (Alpha Build 80)

### ISSUE THREAD

**Issue by Juliandev02** [Vanilla-OS/iso-builder#248]
### Issue Description

Today I tried to install VanillaOS 2.0 Alpha Build 80 [(from this GitHub Action Run)](https://github.com/Vanilla-OS/live-iso/actions/runs/6454386217) and the installation was success. After restarting, it didn't boot and I got thown in the GRUB command line mode. Same thing happens also on VMware Workstation which worked for me perfectly with VanillaOS. And yes I'm using UEFI.
![image](https://github.com/Vanilla-OS/live-iso/assets/81520713/c2cfe8a3-a795-4ceb-92be-de8d019f4b05)

### Steps to Reproduce

- Install VanillaOS 2.0 Alpha Build 80
- Reboot after the Installation was successfully

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

My PC:
- UEFI, SecureBoot, AMD CPU & GPU, SATA SSD

VMware:
- UEFI, no SecureBoot, SATA Interface

**Comment by jsarkari** [comment]
I had the same problem, so I turned off UEFI and it booted, but keeps going back into setup mode.

**Comment by Juliandev02** [comment]
wow what the hell? The build is non-UEFI only?!

**Comment by jsarkari** [comment]
It fails to fully install for me on both GNOME Boxes and Oracle VirtualBox, same as the last release

**Comment by AhriVastaya** [comment]
I'm having the same issue, and disabling UEFI isn't an option as my laptop doesn't support Legacy/BIOS boot. I've used the default install options. I'm able to navigate to the root partitions using the grub shell, but haven't yet figured out how to load the right images/kernel with the ABRoot system.

Currently using a Lenovo thinkpad from 2022 (ACH7)

**Comment by nonetrix** [comment]
Same, I might try reinstalling grub from a liveusb. However, it's worth noting I ran the installer as root from a terminal because the installer freezed at region selection, also I booted from Ventoy on a 500GB SSD inside my computer. Running the installer as a normal user just caused the installer not to open with something about timing out, and running as root came up with a lot of dbus warnings but ultimately "successfully installed". Also, the liveusb felt extremely sluggish and seemed to have poor disk O/I, to the point that I thought that it was the issue and booted from RAM (this did not fix the slow I/O, even file manager took a while to open even on a RAM disk). But to open it in a terminal I had to go to settings, then applications, then terminal, because for some reason GNOME is locked down and didn't let me go to dash, overview, or anything, only quick settings in the top right worked

**Comment by nonetrix** [comment]
> ### Issue Description
> Today I tried to install VanillaOS 2.0 Alpha Build 80 [(from this GitHub Action Run)](https://github.com/Vanilla-OS/live-iso/actions/runs/6454386217) and the installation was success. After restarting, it didn't boot and I got thown in the GRUB command line mode. Same thing happens also on VMware Workstation which worked for me perfectly with VanillaOS. And yes I'm using UEFI. ![image](https://user-images.githubusercontent.com/81520713/274385056-c2cfe8a3-a795-4ceb-92be-de8d019f4b05.png)
> 
> ### Steps to Reproduce
> * Install VanillaOS 2.0 Alpha Build 80
> * Reboot after the Installation was successfully
> 
> ### On what version of Vanilla OS this happens?
> Unreleased
> 
> ### Additional Information
> My PC:
> 
> * UEFI, SecureBoot, AMD CPU & GPU, SATA SSD
> 
> VMware:
> 
> * UEFI, no SecureBoot, SATA Interface

Did the one prior to 80 work? I might just install that, then upgrade hopefully bypassing this

**Comment by Juliandev02** [comment]
> Did the one prior to 80 work? I might just install that, then upgrade hopefully bypassing this

Yes. At least for me in VMware & for others in VBox afaik

**Comment by Thatoo** [comment]
It was working with EFI till the 79 (legacy was not working).

I confirm that 80 won't boot after install on Virtualbox.

**Comment by Juliandev02** [comment]
Fixed with VanillaOS 2.0 Alpha Build **82** (https://github.com/Vanilla-OS/live-iso/actions/runs/6526023055).
Tested devices:
- VMware
