### ISSUE TITLE
Tunelled TLS With PAP Inner Authentication Not Working

### ISSUE THREAD

**Issue by MertKalkanci** [Vanilla-OS/iso-builder#270]
### Issue Description

I can't connect to my schools network. They use Tunelled TLS with PAP inner authentication, even if I  enter my password, username true and use the true certificate I can't connect. 

Also I am able to connect same network on Windows. They have Mac addres registration on their system so I modified my mac address to make it same with the windows and I made it. And in system it shows my ip addres related to that mac addres.

I will ask some of my friends that use other linux distrubations on university to confirm is it school related.

### Steps to Reproduce

present root a, installed Vanilla OS recently.
Just installed tuxedo control center on both roots to control fan speed settings.

### On what version of Vanilla OS this happens?

22.10

**Comment by kbdharun** [comment]
My institution uses the same kind of setup (WPA & WPA2 Enterprise; Tunnelled TLS with PEAP), Vanilla OS 22.10 works (the last time I tested Kinetic on bare metal it worked fine for me, I haven't tested it for 2.0 yet. @matbme Daily drives 2.0 so he can confirm if it works from his institution's network).

Edit. Nvm, thought your issue was for 2.0, since it's 22.10 it should work.

Btw, If you are on the same device and dual boot, I am pretty sure both Windows and Linux will share the same Mac address if you are trying to modify the Mac address of a different device and make it work; the WPA & WPA2 Enterprise Wifi security wouldn't allow your device to connect to the network and this issue might not just be limited to Vanilla OS.

**Comment by MertKalkanci** [comment]
> My institution uses the same kind of setup (WPA & WPA2 Enterprise; Tunnelled TLS with PEAP), Vanilla OS 22.10 works (the last time I tested Kinetic on bare metal it worked fine for me, I haven't tested it for 2.0 yet. @matbme Daily drives 2.0 so he can confirm if it works from his institution's network).
> 
> Edit. Nvm, thought your issue was for 2.0, since it's 22.10 it should work.
> 
> Btw, If you are on the same device and dual boot, I am pretty sure both Windows and Linux will share the same Mac address if you are trying to modify the Mac address of a different device and make it work; the WPA & WPA2 Enterprise Wifi security wouldn't allow your device to connect to the network and this issue might not just be limited to Vanilla OS.

Yes you are right, I will reset mac adress and retry with the new mac adress after my lecture. I will notify when I try.

**Comment by MertKalkanci** [comment]
Well I fixed it and the reason behind it was my instutuision. When I red the logs with wpa gui app I saw that the sertificate they gave me was not the sertifiicate that I had to use. In logs I saw that they use Digi Cert Root 2 certificate so I downloaded .pem certificate manually from their website and when i used it the issue solved. I emailed them to update sertificates on their website. Also thank you guys for your help.
