### ISSUE TITLE
Unable to execute commands as root using sudo su

### ISSUE THREAD

**Issue by RaulKong898** [Vanilla-OS/iso-builder#290]
### **Issue Description**

When attempting to execute commands as root using the sudo su command, the command prompt simply reappears without executing the command. No error messages are displayed. Attempting to run certain commands without using sudo su results in a prompt to run them with root privileges, but the sudo su command remains ineffective.

### **Steps to Reproduce**

1. Open a terminal window.
2. Type the command sudo su and press Enter.
3. Observe that the command prompt reappears without executing the command.
4. Optionally, attempt to run a command that requires root privileges without using sudo su and observe the prompt to use root privileges.

### **On what version of Vanilla OS this happens?**

Unreleased

**Comment by RaulKong898** [comment]
![Uploading Screenshot from 2024-01-01 15-37-03.png…]()

**Comment by RaulKong898** [comment]
![Screenshot from 2024-01-01 15-37-03](https://github.com/Vanilla-OS/live-iso/assets/121046976/18f084be-4ab8-4bae-a56e-afdcbc18c52a)

**Comment by mirkobrombin** [comment]
Please take note you are inside the VSO container. In Orchid the shell defaults to VSO to prevent you from breaking the host system. The sideload utility cannot be reached from there, you should use it by its GUI or using `host-spawn <command>` where `<command>` is the command you want to spawn on host, e.g. `host spawn vanilla-sideload --install`, but that could make no sense since the sideload utility always install packages inside the VSO container, not the system.

To sideload a package in VSO you just have to open your console (which will prompt you the VSO shell, then `dpkg -i <package_path>`.

Commands like apx and abroot are always available inside the VSO shell but they operate on the host system. Currently there is a problem with ABRoot, it does not work from inside VSO, so you have to run it with `host-spawn sudo abroot`

**Comment by mirkobrombin** [comment]
Closing as per non activity.
