### ISSUE TITLE
vanillaos kinetic attempts to connect to old repo urls

### ISSUE THREAD

**Issue by mcwimpy** [Vanilla-OS/iso-builder#324]
### Screenshots & Logs

- [vanilla-install-2024-04-15d.txt](https://github.com/Vanilla-OS/live-iso/files/14997371/vanilla-install-2024-04-15d.txt)
- [vanilla-install-2024-04-15c.txt](https://github.com/Vanilla-OS/live-iso/files/14997372/vanilla-install-2024-04-15c.txt)
- [vanilla-install-2024-04-15b.txt](https://github.com/Vanilla-OS/live-iso/files/14997373/vanilla-install-2024-04-15b.txt)
- [vanilla-install-2024-04-15a.txt](https://github.com/Vanilla-OS/live-iso/files/14997374/vanilla-install-2024-04-15a.txt)

| | | |
|--------|--------|--------|
| ![Screenshot from 2024-04-16 13-23-53](https://github.com/Vanilla-OS/live-iso/assets/11300847/414fb055-1a56-4fe0-825c-088bc9084c0f) | ![Screenshot from 2024-04-16 13-22-27](https://github.com/Vanilla-OS/live-iso/assets/11300847/c942bd93-00f4-4d16-831d-4cccdb3bc488) | ![Screenshot from 2024-04-16 13-21-25](https://github.com/Vanilla-OS/live-iso/assets/11300847/046741b7-7d88-4fc3-ab10-632b52a855bc) | 

### Steps to Reproduce

do what the installer wants

### On what version of Vanilla OS this happens?

22.10

**Comment by mcwimpy** [comment]
![Screenshot from 2024-04-16 13-31-57](https://github.com/Vanilla-OS/live-iso/assets/11300847/c952c62b-471e-4b70-b7ea-baac4f726fb5)

**Comment by axtloss** [comment]
From the logs you included (which, with the screenshots, are pretty much the only useful thing in this novel of a bug report) it appears that the installer still tries to contact old repository urls.
Did you make sure that you are using the latest kinetic url? I believe this issue has been resolved before, as the ISOs are configured to use the now correct urls.

**Comment by mirkobrombin** [comment]
As axtloss noted, it appears from the logs and screenshots that there’s an issue with outdated repository URLs, which we addressed last [October](https://github.com/Vanilla-OS/live-iso/commit/660141606c0b80a508846deb79320343a8457179), so please ensure you are using the latest ISO or provide the source you used. Please remember that it is crucial to keep bug reports technical and straightforward. This helps us investigate issues more quickly. For more general discussions or feedback, please use our designated channels such as Discord.

**Comment by TheEvilSkeleton** [comment]
I've taken the liberty to edit the issue description

**Comment by taukakao** [comment]
The installer correctly connects to old-releases because kinetic is an "old release". 
But just to make sure, I just installed the version provided here https://github.com/Vanilla-OS/live-iso/releases/tag/22.10-r9 and it fully installed inside a VM in less then 10 minutes.

I'm sorry to hear that you had trouble installing. If you have a more specifc problem, please open an issue that has only the related information and logs. 
From the fact that the kinetic installer is stable I'm gonna assume that it has to do with your specific hardware. 

For the general complaints about vanilla, I would recommend using our other channels as mirko pointed out, or use a personal blog.
