### ISSUE TITLE
Installation window/popup disappears randomly

### ISSUE THREAD

**Issue by iocron** [Vanilla-OS/iso-builder#356]
### Issue Description

During the Vanilla OS Installation Process the Install Window disappears after a while. 

### Steps to Reproduce

During the Vanilla OS Installation Process the Install Window disappears after a while. I've tried 2 different USB-A Drives and I've used Etcher to write the ISO (VanillaOS-2-stable.20240805.iso) to the USB-A Drives. I've tried the installation 3 times, one time the Install Window disappeared very early at the beginning (I think during the language options), then 2 times at the end (after confirmation to finally install Vanilla OS). 

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

### Additional Information

I am using a fresh new Framework Laptop 16 (https://frame.work/de/en/products/laptop16-diy-amd-7040), which has a Ryzen 7 7840HS, and without dedicated graphics card.

**Comment by theklinks** [comment]
Same issue occurs on Dell OptiPlex 7040 Micro. Occurs with the Stable ISO and with Beta builds 6/25/2024, 7/12/2024, 7/22/2024, and 7/28/2024. CachyOS, Pop!_OS, Fedora Kinoite, and Vanilla OS 22.10 Kinetic work just fine on the same hardware.

**Comment by DeWir3** [comment]
Same has been happening for me on a StarLabs StarLite 5. Unfortunately I cannot confirm at the moment whether the recently uploaded VanillaOS-2-stable.20240824.iso fixes the issue.

**Comment by theklinks** [comment]
Good news: VanillaOS-2-stable.20240824.iso installs successfully on that Dell OptiPlex 7040 Micro. 

Bad news: it doesn't appear to make the correct boot entries in the system's firmware. There's an entry for "vanilla" and an entry for "debian" but neither appear to work. Both entries "vanilla" point to \EFI\BOOT\BOOTX64.EFI. Manually creating an entry pointing to \EFI\debian\grubx64.efi or \EFI\debian\shimx64.efi doesn't appear to fix the issue as the entry's value reverts to \EFI\BOOT\BOOTX64.EFI.

This machine is on the most recent BIOS revision, 1.24.0. Specs:
- CPU: Intel Core i5-6500T (4c/4t, 2.50GHz base, 3.10GHz max turbo, 35W TDP)
- RAM: 16GB DDR4-2133
- Storage: Samsung PM981a 512GB NVMe SSD, Samsung 883 DCT 3.84TB SATA SSD
- Wifi: Realtek RTL8822CE (system didn't ship with it, pulled from my HP Dev One)

BIOS settings are loose enough to allow the installer to update them: TPM disabled/hidden, secure boot disabled, CSM disabled, admin/user/storage passwords disabled. 

I have a Lenovo ThinkPad E595 with a similar storage layout (512 PM981a + 960GB Micron 5200 Pro) and haven't had any trouble with the Vanilla OS install, so I can't say it's the storage layout that's the problem here.

**Comment by mirkobrombin** [comment]
> Good news: VanillaOS-2-stable.20240824.iso installs successfully on that Dell OptiPlex 7040 Micro.
> 
> Bad news: it doesn't appear to make the correct boot entries in the system's firmware. There's an entry for "vanilla" and an entry for "debian" but neither appear to work. Both entries "vanilla" point to \EFI\BOOT\BOOTX64.EFI. Manually creating an entry pointing to \EFI\debian\grubx64.efi or \EFI\debian\shimx64.efi doesn't appear to fix the issue as the entry's value reverts to \EFI\BOOT\BOOTX64.EFI.
> 
> This machine is on the most recent BIOS revision, 1.24.0. Specs:
> 
> * CPU: Intel Core i5-6500T (4c/4t, 2.50GHz base, 3.10GHz max turbo, 35W TDP)
> * RAM: 16GB DDR4-2133
> * Storage: Samsung PM981a 512GB NVMe SSD, Samsung 883 DCT 3.84TB SATA SSD
> * Wifi: Realtek RTL8822CE (system didn't ship with it, pulled from my HP Dev One)
> 
> BIOS settings are loose enough to allow the installer to update them: TPM disabled/hidden, secure boot disabled, CSM disabled, admin/user/storage passwords disabled.
> 
> I have a Lenovo ThinkPad E595 with a similar storage layout (512 PM981a + 960GB Micron 5200 Pro) and haven't had any trouble with the Vanilla OS install, so I can't say it's the storage layout that's the problem here.

please open a new issue in the vanilla-installer repo for that.

Closing since fixed.
