### ISSUE TITLE
broadcom wireless drivers not detected in the vanilla control center

### ISSUE THREAD

**Issue by alihassan1989** [Vanilla-OS/iso-builder#37]
I got it to work. I installed debian a while ago and I had the same issue. so I wrote a guide on how to fix it and I applied it on vanilla os and it worked. here is the guide: https://github.com/alihassan1989/dotfile/blob/main/config/broadcom-debian

instead of "sudo apt-get install broadcom-sta-" it must be "sudo abroot exec apt install broadcom-sta-" and so on.
and you must reboot your system for the changes to take effect, so expect to reboot your system few times in order for your wifi to work.

I think installing network-manager is not necessary in Gnome. I wrote this guide when I was using DWM.

can you please verify/validate those steps to make sure that it will not cause any harm to the file system. thank you

**Comment by IIMustangII1151** [comment]
I have an iMac 7.1 mid 2007 with Broadcom Wi-Fi card and it didn't work for me

**Comment by alihassan1989** [comment]
Have you tried any of the solutions provided in the link? I use an older MacBook pro and it worked for me

**Comment by rantnar** [comment]
Solution from debian that worked for me:
`sudo abroot exec apt install linux-headers-$(uname -r|sed 's,[^-]*-[^-]*-,,') broadcom-sta-dkms`

**Comment by mirkobrombin** [comment]
Broadcom drivers should appear in the Drivers tab of the Vanilla Control Center. If not, that driver is not supported by the ubuntu-drivers utility and should be reported to the Ubuntu developers. As suggested by rantnar you can still install it manually.

**Comment by sgon00** [comment]
Will this bug be fixed in next debian based version? I am having BCM4360 Wifi card and running MX Linux (debian-based) KDE right now. Everything works out-of-box in MX Linux (KDE). Today, I heard vanilla os and tried the live system. Wifi card can not be detected. Well, maybe it can be fixed somehow, but I don't really try. My laptop does not have an ethernet card. Nowadays, it's hard to do anything without a network. So my vanilla OS attempt ended here because of no network. Hopefully, the problem will be fixed in debian based system and I will try it again when the next version is released. Thanks. 

**[Edited]** Since nobody replied, I will not try vanilla OS anymore. I will keep using MX Linux (KDE) in the future then.
Thus, I don't expect any replies to this post.
