### ISSUE TITLE
Unable to boot after install (no UEFI BIOS entry to boot from)

### ISSUE THREAD

**Issue by r1n0x** [Vanilla-OS/iso-builder#372]
### Issue Description

Hey,
I just bricked my fully working Debian 12 installation by running "sudo apt remove python3" (wanted to downgrade from 3.11.2 to 3.10.15 cause some AI garbage didn't work with 3.11+) 🤡. There are some ideas on the internet on how to fix that but I don't have internet connection due to VPN kill swich which I don't know how to turn on without GUI 💀 

I've been looking into Vanilla OS recently and really wanted to try it out on my machine so I downloaded .iso file from https://vanillaos.org/download/orchid/stable and after installing with UEFI BIOS there is no UEFI Boot entry to boot from, I only have my windows entry.

Some other things:
1. I have 4 physical drives (obviosuly installing vanilla on something other than windows disk, same one which had working debian)
2. Installing vanilla removed my debian uefi bios entry
3. Tried encrypted and unencrypted mode
4. ISO filename is "VanillaOS-2-stable.20240824" which appears to be newest, so it should include 
https://github.com/Vanilla-OS/vanilla-installer/issues/380
5. After installation I've tried legacy bios mode and there was no bios entry to be found too :(
6. Used automatic partitioning
7. Installed from USB with ventoy

I really wanna try Vanilla out so I hope you guys can help! Lemme know if you want anything (I can reinstall it and get logs or something, it takes like 3 minutes to install so feel free).

### Steps to Reproduce

Believe me

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

### Additional Information

Clone of https://github.com/Vanilla-OS/vanilla-installer/issues/428 - i dont know which repo to report this in

**Comment by r1n0x** [comment]
Ima just continue to use debian boys

**Comment by DevelAngel** [comment]
I can confirm this error with the live iso from 2024-08-24.

The version from 2024-08-05 has not shown this problem on another laptop. But I will check this, too.

**Comment by DevelAngel** [comment]
It seems that the UEFI bootloader of your computer cannot start GRUB.

I tried to install Vanilla-OS into a VirtualBox VM and ended up with the following error

```
Booting UEFI ORCL-VBOX-NVME-VER12 ...
BdsDxe: failed to load Boot0002 "UEFI ORCL-VBOX-NVME-VER12 ..."
BdsDxe: No bootable option or device was found.
```

I tried to create a "startup.nsh" in the efi partition but that had not worked.

The trick that worked was to reinstall GRUB as follows:

1. Boot again the VanillaOS Live System
2. Select Recovery
3. Select Console
4. In the console window, type the following:

```console
$ lsblk

$ sudo mount /dev/nvme0n1p1 /mnt
$ sudo mount /dev/nvme0n1p2 /mnt/efi
$ sudo /sbin/grub-install /dev/nvme0n1 --boot-directory=/mnt --efi-directory=/mnt/efi --target=x86_64-efi --bootloader-id=GRUB --removable
```

Via `lsblk`, you can find out your boot partitions. For me, I used the default settings from VanillaOS Installer so that it is `/dev/nvme0n1p1` (boot partition) and `/dev/nvme0n1p2` (efi partition). And grub is installed into `/dev/nvme0n1` (without p1/p2).

**Comment by DevelAngel** [comment]
I think that `--removable` was the solution for virtualbox.

But in your situation, it could be also a problem in your  UEFI settings..
