### ISSUE TITLE
Ability to edit kernel parameters

### ISSUE THREAD

**Issue by AussieAnon** [Vanilla-OS/iso-builder#50]
Looking to add amdgpu.ppfeaturemask=0xffffffff to my GRUB config so that I can undervolt and overclock my GPU with CoreCtrl.

So far, I do not believe we can edit the grub config and have it save successfully.

Would also love to include "quiet loglevel=0". #38

**Comment by wolfiediscord** [comment]
This would be great. Currently, it is not possible to use hibernation mode on VanillaOS, since the GRUB config gets overwritten every time there is an update. Unfortunately, I rely heavily on hibernation mode to save my battery life, so this is a block for me using VanillaOS.

Edit: Upon further inspection, it looks like it is possible to modify kernel parameters using ABRoot already, [as stated in the documentation.](https://documentation.vanillaos.org/docs/ABRoot/#title3)

I think this should be included in some sort of FAQ for more advanced users of linux.

**Comment by mirkobrombin** [comment]
It is now possible: https://documentation.vanillaos.org/docs/ABRoot/#title3

Make sure you have the latest ABRoot version: `sudo abroot exec apt upgrade`.
