### ISSUE TITLE
Display a warning when users try to run `apt` and `dpkg` from the host

### ISSUE THREAD

**Issue by mks-h** [Vanilla-OS/iso-builder#57]
### Feature Description

On `apt` and `dpkg` invocation, show a message to use apx or abroot, instead.

### Rationale

People often go to Discord and ask how to install things after figuring there's no APT installed.

**Comment by mirkobrombin** [comment]
Thanks for your report.

This was expected in early releases of Vanilla OS but was removed because it needs to be understood that Vanilla OS is not "truly" Ubuntu and the user is encouraged to learn the workflow using the [handbook](https://handbook.vanillaos.org/2023/01/11/install-and-manage-applications.html).
